#!/usr/bin/env bash

case "$1" in
   "i")
      osm vnfd-create hydra_server_vnf.tar.gz
      osm vnfd-create hydra_client_2tx_2rx_vnf.tar.gz
      osm vnfd-create hydra_rx1_vnf.tar.gz
      osm vnfd-create hydra_rx2_vnf.tar.gz
      osm nsd-create  basic_ns.tar.gz
   ;;
   "l")
#      osm vnfd-list
#      osm nsd-list
      osm ns-list
   ;;
   "d")
      osm nsd-delete basic_nsd
      osm vnfd-delete hydra_server
      osm vnfd-delete hydra_client_2tx_2rx
      osm vnfd-delete hydra_rx1
      osm vnfd-delete hydra_rx2
   ;;
   "nc")
      ./osm d
      ./osm i
      osm ns-create --ns_name basic --nsd_name basic_nsd --vim_account PREPRODUCTION
      #osm ns-create --ns_name basic --nsd_name basic_nsd --vim_account PRODUCTION_WINS_5G
   ;;
   "nd")
      osm ns-delete basic
      osm nsd-delete basic_nsd
   ;;
   "jd")
      juju remove-machine --force ${@:2}
      juju remove-application basic-b-vnfd
      juju remove-application basic-c-vnfd
      juju remove-application basic-d-vnfd
   ;;
   *)
      echo "[i]nstall"
      echo "[l]ist"
      echo "[d]elete"
      echo "[nc]s-create"
      echo "[nd]s-delete"
      echo "[jd]uju-delete"
   ;;
esac
