#!/usr/bin/env python3

import sys
sys.path.append('lib')

from charms.reactive import main
from charms.reactive import set_state
from charmhelpers.core.hookenv import action_fail

set_state('actions.start-hydra-aas')

try:
    main()
except Exception as e:
    action_fail(repr(e))