- hosts: receivers
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
      vars:
        packages:
          - libzmq3-dev
          - libfftw3-dev
          - libopencv-dev
          - gnuradio
          - gnuradio-dev
      become: yes

    - name: Get source for GR-Hydra
      git:
        repo: "https://github.com/maiconkist/gr-hydra.git"
        dest: /home/ubuntu/gr-hydra
        version: bleeding
        update: true
        force: yes
    
    - name: Make HyDRA Directory
      file:
        path: /home/ubuntu/gr-hydra/build
        state: directory
    - name: CMake HyDRA
      command: cmake ../
      args:
        chdir: /home/ubuntu/gr-hydra/build
    - make:
        chdir: /home/ubuntu/gr-hydra/build
    - make:
        chdir: /home/ubuntu/gr-hydra/build
        target: install
      become: yes

    - name: Make GRC-HyDRA Directory
      file:
        path: /home/ubuntu/gr-hydra/grc_blocks/build
        state: directory
    - name: CMake HyDRA
      command: cmake ../
      args:
        chdir: /home/ubuntu/gr-hydra/grc_blocks/build
    - make:
        chdir: /home/ubuntu/gr-hydra/grc_blocks/build
    - make:
        chdir: /home/ubuntu/gr-hydra/grc_blocks/build
        target: install
      become: yes
  
    - name: chmod  /home/ubuntu/gr-hydra/grc_blocks/app/ansible_vr1_rx.py
      file:
        path: /home/ubuntu/gr-hydra/grc_blocks/app/ansible_vr1_rx.py
        state: file
        mode: a+x
      
    - name: Start ansible_vr1_rx.py script. Log to /tmp/
      shell: nohup /home/ubuntu/gr-hydra/grc_blocks/app/ansible_vr1_rx.py >> /tmp/ansible_hydra_vr1_rx.log &
